Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -109,6 +109,12 @@ permissions:
         type: boolean
         default: false
 
+      add_nomount:
+        description: 'Add NoMount support'
+        required: false
+        type: boolean
+        default: false
+
       resukisu_multi_manager:
         description: "使用原 SukiSU 管理器"
         required: true
@@ -408,6 +414,48 @@ jobs:
             patch -p1 -F 3 --fuzz=5 < unicode_bypass_fix_6.1-.patch || true
           fi
 
+      - name: NoMount
+        if: ${{ inputs.add_nomount }}
+        run: |
+          echo ""
+          echo "=== NoMount patch ==="
+          cd "$KERNEL_ROOT/common" # cd "$CONFIG/common"
+          if [ "${{ inputs.cancel_susfs }}" == "true" ]; then
+            echo "  no susfs"
+            NOMOUNT_PATCH="nomount-kernel-5.10.patch"
+          else
+            echo "  with susfs"
+            NOMOUNT_PATCH="nomount-susfs-kernel-5.10.patch"
+          fi
+          MASTER_EXP="master" # master experimental
+          curl -LSs "https://raw.githubusercontent.com/maxsteeel/nomount/refs/heads/$MASTER_EXP/patches/$NOMOUNT_PATCH" -o nomount.patch
+          chmod 777 nomount.patch
+          echo "Applying..."
+          patch -p1 < nomount.patch # > patch_nomount_log.txt 2>&1
+          #NOMOUNT_PATCH_EXIT_CODE=$?
+          #if [ $NOMOUNT_PATCH_EXIT_CODE -ne 0 ]; then
+          #  echo "ERROR nomount patch: $NOMOUNT_PATCH_EXIT_CODE"
+          #else
+          NAME_INFO="${{ env.NAME_INFO }}_NoMount"
+          echo "${{ inputs.kernelsu_variant }} NAME_INFO=$NAME_INFO"
+          echo "NAME_INFO=$NAME_INFO" >> $GITHUB_ENV
+          #fi
+          
+          #echo "CONFIG_NOMOUNT=y" >> "${{ env.DEFCONFIG_FRAGMENT }}"
+          DEFCONFIG="common/arch/arm64/configs/gki_defconfig"
+          echo "CONFIG_NOMOUNT=y" >> $DEFCONFIG;
+
+          NAME_INFO="${{ env.NAME_INFO }}"
+          if [ "${{ inputs.bypass_unicode }}" == "true" ]; then NAME_INFO="${NAME_INFO}_uni"; fi
+          #if [ "${{ inputs.cancel_susfs }}" == "false" ]; then NAME_INFO="${NAME_INFO}_uni"; fi
+          if [ "${{ inputs.use_zram }}" == "true" ]; then NAME_INFO="${NAME_INFO}_zram"; fi
+          if [ "${{ inputs.use_bbg }}" == "true" ]; then NAME_INFO="${NAME_INFO}_bbg"; fi
+          if [ "${{ inputs.use_kpm }}" == "true" ]; then NAME_INFO="${NAME_INFO}_kpm"; fi
+          if [ "${{ inputs.enable_tmpfs }}" == "true" ]; then NAME_INFO="${NAME_INFO}_tmpfs"; fi
+          if [ "${{ inputs.cancel_susfs }}" == "false" ]; then NAME_INFO="${NAME_INFO}_susfs"; fi
+          echo "${{ inputs.kernelsu_variant }} NAME_INFO=$NAME_INFO"
+          echo "NAME_INFO=$NAME_INFO" >> $GITHUB_ENV
+
       - name: 配置 Defconfig
         run: |
           cd "$CONFIG"
@@ -497,7 +545,7 @@ jobs:
 
            cd AnyKernel3
            cp ../$CONFIG/out/${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}/dist/Image ./
-           ZIP_NAME="GKI-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.${{ env.SUB_LEVEL }}-${{ env.OS_PATCH_LEVEL }}-${{ inputs.kernelsu_variant }}.zip"
+           ZIP_NAME="GKI-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.${{ env.SUB_LEVEL }}-${{ env.OS_PATCH_LEVEL }}-${{ inputs.kernelsu_variant }}${{ env.NAME_INFO }}.zip"
            zip -r "$ZIP_NAME" ./*
            echo "ZIP_PATH=$GITHUB_WORKSPACE/AnyKernel3/$ZIP_NAME" >> $GITHUB_ENV
 
@@ -531,7 +579,8 @@ jobs:
       - name: 上传产物
         uses: actions/upload-artifact@v4
         with:
-          name: Kernel_Build_Output
+          #name: Kernel_Build_Output
+          name: ${{ inputs.kernelsu_variant }}_kernel-${{ env.CONFIG }}${{ env.NAME_INFO }}
           path: |
             ${{ env.ZIP_PATH }}
             *.img
